title: Shakhawat Hossain
url: "https://Shakhawat.me/"
baseurl: "/portfoliotest"

markdown: kramdown


tracking_id: #

footer: yes
footer_url: "https://Shakhawat.me"
footer_text: "Page design by Shakhawat"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/portfoliotest"
 - name: "Blog"
   link: "https://blog.shakhawat.me"
 - name: "Contact"
   link: "contact"
